#+title: khcalc

This is an ongoing project building toward an implementation of Queffelec-Rose style constructions of colored sl_{n}/gl_{n} link invariants.

** Current Status
khcalc currently computes the HOMFLY-PT polynomial of a braid closure from the Hecke algebra and Jones-Ocneanu (Markov) trace directly. Below is an example calculation for the right-handed trefoil.

#+begin_src python :results output
from braid import BraidElem
from trace import homfly_from_braid as homfly

tref = BraidElem(2, (1,1,1)) #right-handed trefoil
print(homfly(tref))

#OUTPUT: (-q^-3*a^-2 + q^-1*a^-4 + q^-1*a^-2 - q*a^-4 - q*a^-2 + q^3*a^-2)/(-q^-1 + q)
#+end_src

** Future Plans
The current implementation provides a decategorified model of type A Reshetikhin-Turaev invariants, and will serve as the foundation for implementations of more subtle categorified constructions.

This project is oriented toward working directly in Khovanov-Lauda-Rouquier (quiver Hecke) algebras as the primary algebraic framework, together with their foam 2-representations, in order to compute (un)colored sl_n link homologies of braid closures.
